//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pixir.Not.View2.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        public static string MES_FECHA_IGUAL_POSTERIOR_HOY { get; internal set; }
        public static string MES_EDAD_MENOR_18_ANOS { get; internal set; }

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pixir.Not.View2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido paterno vacio.
        /// </summary>
        internal static string MES_APELLIDO_PATERNO_VACIO {
            get {
                return ResourceManager.GetString("MES_APELLIDO_PATERNO_VACIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busqueda vacia.
        /// </summary>
        internal static string MES_BUSQUEDA_VACIA {
            get {
                return ResourceManager.GetString("MES_BUSQUEDA_VACIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado civil vacio.
        /// </summary>
        internal static string MES_COM_CAT_ESTADO_CIVIL_VACIO {
            get {
                return ResourceManager.GetString("MES_COM_CAT_ESTADO_CIVIL_VACIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nacionalidad vacia.
        /// </summary>
        internal static string MES_COM_CAT_NACIONALIDAD_VACIO {
            get {
                return ResourceManager.GetString("MES_COM_CAT_NACIONALIDAD_VACIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocupacion vacia.
        /// </summary>
        internal static string MES_COM_CAT_OCUPACION_VACIO {
            get {
                return ResourceManager.GetString("MES_COM_CAT_OCUPACION_VACIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regimen matrimoial vacio.
        /// </summary>
        internal static string MES_COM_CAT_REGIMEN_MATRIMONIAL_VACIO {
            get {
                return ResourceManager.GetString("MES_COM_CAT_REGIMEN_MATRIMONIAL_VACIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sexo vacio.
        /// </summary>
        internal static string MES_COM_CAT_SEXO_VACIO {
            get {
                return ResourceManager.GetString("MES_COM_CAT_SEXO_VACIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado civil sin seleccionar.
        /// </summary>
        internal static string MES_COMBOBOX_ESTADO_CIVIL_SIN_SELECCIONAR {
            get {
                return ResourceManager.GetString("MES_COMBOBOX_ESTADO_CIVIL_SIN_SELECCIONAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nacionalidad sin seleccionar.
        /// </summary>
        internal static string MES_COMBOBOX_NACIONALIDAD_SIN_SELECCIONAR {
            get {
                return ResourceManager.GetString("MES_COMBOBOX_NACIONALIDAD_SIN_SELECCIONAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocupacion sin seleccionar.
        /// </summary>
        internal static string MES_COMBOBOX_OCUPACION_SIN_SELECCIONAR {
            get {
                return ResourceManager.GetString("MES_COMBOBOX_OCUPACION_SIN_SELECCIONAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sexo sin seleccionar.
        /// </summary>
        internal static string MES_COMBOBOX_SEXO_SIN_SELECCIONAR {
            get {
                return ResourceManager.GetString("MES_COMBOBOX_SEXO_SIN_SELECCIONAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CURP duplicada.
        /// </summary>
        internal static string MES_CURP_DUPLICADA {
            get {
                return ResourceManager.GetString("MES_CURP_DUPLICADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CURP con formato incorrecto.
        /// </summary>
        internal static string MES_CURP_INCORRECTA {
            get {
                return ResourceManager.GetString("MES_CURP_INCORRECTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entidad vacia.
        /// </summary>
        internal static string MES_ENTIDAD_VACIA {
            get {
                return ResourceManager.GetString("MES_ENTIDAD_VACIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro no existe.
        /// </summary>
        internal static string MES_NO_EXISTE_REGISTRO {
            get {
                return ResourceManager.GetString("MES_NO_EXISTE_REGISTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre vacio.
        /// </summary>
        internal static string MES_NOMBRE_VACIO {
            get {
                return ResourceManager.GetString("MES_NOMBRE_VACIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizado con exito.
        /// </summary>
        internal static string MES_OPERACION_EXITO_ACTUALIZAR {
            get {
                return ResourceManager.GetString("MES_OPERACION_EXITO_ACTUALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editado con exito.
        /// </summary>
        internal static string MES_OPERACION_EXITO_EDITAR {
            get {
                return ResourceManager.GetString("MES_OPERACION_EXITO_EDITAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminado con exito.
        /// </summary>
        internal static string MES_OPERACION_EXITO_ELIMINAR {
            get {
                return ResourceManager.GetString("MES_OPERACION_EXITO_ELIMINAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardado con exito.
        /// </summary>
        internal static string MES_OPERACION_EXITO_GUARDAR {
            get {
                return ResourceManager.GetString("MES_OPERACION_EXITO_GUARDAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Originario vacio.
        /// </summary>
        internal static string MES_ORIGINARIO_VACIO {
            get {
                return ResourceManager.GetString("MES_ORIGINARIO_VACIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona duplicada, CURP en BD llena.
        /// </summary>
        internal static string MES_PERSONA_DUPLICADA_CURP_ENBD_LLENA {
            get {
                return ResourceManager.GetString("MES_PERSONA_DUPLICADA_CURP_ENBD_LLENA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona duplicada, CURP nueva llena.
        /// </summary>
        internal static string MES_PERSONA_DUPLICADA_CURP_NUEVA_LLENA {
            get {
                return ResourceManager.GetString("MES_PERSONA_DUPLICADA_CURP_NUEVA_LLENA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona duplicada, CURPS llenos.
        /// </summary>
        internal static string MES_PERSONA_DUPLICADA_CURPS_LLENOS {
            get {
                return ResourceManager.GetString("MES_PERSONA_DUPLICADA_CURPS_LLENOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona duplicada, CURPS vacios.
        /// </summary>
        internal static string MES_PERSONA_DUPLICADA_CURPS_VACIOS {
            get {
                return ResourceManager.GetString("MES_PERSONA_DUPLICADA_CURPS_VACIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un registro.
        /// </summary>
        internal static string MES_SELEECIONAR_REGISTRO {
            get {
                return ResourceManager.GetString("MES_SELEECIONAR_REGISTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo.
        /// </summary>
        internal static string MES_TITULO {
            get {
                return ResourceManager.GetString("MES_TITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario invalido.
        /// </summary>
        internal static string MES_USUARIO_INVALIDO {
            get {
                return ResourceManager.GetString("MES_USUARIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pre cierre editar.
        /// </summary>
        internal static string PRE_CIERRE_EDITAR {
            get {
                return ResourceManager.GetString("PRE_CIERRE_EDITAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pre cierre nuevo.
        /// </summary>
        internal static string PRE_CIERRE_NUEVO {
            get {
                return ResourceManager.GetString("PRE_CIERRE_NUEVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro pre eliminado.
        /// </summary>
        internal static string PRE_ELIMINAR_REGISTRO {
            get {
                return ResourceManager.GetString("PRE_ELIMINAR_REGISTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona singular.
        /// </summary>
        internal static string TIT_PERSONA_SINGULAR {
            get {
                return ResourceManager.GetString("TIT_PERSONA_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema.
        /// </summary>
        internal static string TIT_SISTEMA {
            get {
                return ResourceManager.GetString("TIT_SISTEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VERIFICAR.
        /// </summary>
        internal static string TIT_VERIFICAR {
            get {
                return ResourceManager.GetString("TIT_VERIFICAR", resourceCulture);
            }
        }
    }
}
